config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:create, :index, :show, :edit, :update] do
    resources :secretsnowman, controller: :users, only: [:show, :index]
  end

  resource :session, only: [:destroy]

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post'login' => 'sessions#create'
  root to: redirect("/signup")
end

app/models/hacking_attempt.rb
class HackingAttempt < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  GROUPS = ["Oct 2015 Cohort", "a/A Staff 2016"]

  attr_reader :password
  after_initialize :ensure_session_token, :ensure_default_taste

  validates :email, :session_token, :password_digest,
      :name, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :name, :session_token, uniqueness: true
  validate :not_a_ghost
  validate :new_user_group

  belongs_to :secretsnowman, class_name: :User

  def self.groups
    GROUPS
  end

  def self.assign_secret_santas(group_name)
    user_ids = User.where(group: group_name).pluck(:id)
    offset = rand(user_ids.length - 2) + 1
    snowman_ids = user_ids.drop(offset) + user_ids.take(offset)

    snowman_ids.each_with_index do |el, idx|
      user = User.find(user_ids[idx])
      user.update_attributes(secretsnowman_id: el)
    end

    nil
  end

  def self.remove_secret_santas(group_name)
    users = User.where(group: group_name)

    users.each do |user|
      user.update_attributes(secretsnowman_id: nil)
    end

    nil
  end

  def not_a_ghost
    if group == GROUPS[0]
      errors[:boooo] << " - no hacking!"
      HackingAttempt.create(user_id: 0, description: "Ghost")
    end
  end

  def new_user_group
    errors[:group] << "cannot be blank" if self.id.nil? && GROUPS.index(self.group).nil?
  end

  def ensure_default_taste
    self.taste ||= "\nglow in the dark yoyo, \nglow in the dark socks,\na cute lunchbox,\na hug".html_safe
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return nil if user.nil?
    user && user.valid_password?(password) ? user : nil
  end

  def self.find_by_name_and_pw(name, password)
    user = User.find_by(name: name)

    return nil if user.nil?
    user && user.valid_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  private
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def require_login!
    redirect_to login_url unless logged_in?
  end

  def logged_in?
    !!current_user
  end

  def log_in!(user)
    @current_user = user
    session[:session_token] = current_user.reset_session_token!
  end

  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_name_and_pw(
      params[:user][:name],
      params[:user][:password]
    )

    if user
      log_in!(user)
      redirect_to users_url
    else
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    end
  end

  def new
  end

  def destroy
    log_out!
    redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :require_login!, only: [:index, :show, :edit, :update]

  def create
    @user = User.new(user_params)
    @user.email ||= "n/a"

    if @user.save
      log_in!(@user)
      flash[:errors] = ["Do not forget to update your wish list."]
      flash[:errors] << ["Go to 'My Profile' to do so."]
      redirect_to users_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    redirect_to users_url if current_user
    @user = User.new
  end

  def index
    @users = User.where(group: current_user.group)

    unless params[:user_id].nil?
      flash.now[:errors] = ["Secret Snowmen have not yet been assigned - but thanks for checking eager beaver!"]
      flash.now[:errors] << ["In the meantime, feel free to check out the wish lists of your team:"]
    end
  end

  def edit
    @user = User.find(params[:id])

    if @user.id != current_user.id
      flash.now[:errors] = ["Bad elf!  You cannot edit someone else's profile!"]
      HackingAttempt.create(user_id: current_user.id, description: "Edit someone else's profile")
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      render :edit
    end
  end

  def show
    if params[:user_id] && params[:user_id].to_i != current_user.id
      flash[:errors] = ['Bad elf!  You cannot view another person\'s secret snowman assignment']
      HackingAttempt.create(user_id: current_user.id, description: "View someone else's secret snowman")
      redirect_to users_url
    elsif params[:user_id] && params[:id].to_i != current_user.secretsnowman_id
      flash[:errors] = ['Nice try buddy!  If you want to view another participants wishlist, simply click on their name below.']
      HackingAttempt.create(user_id: current_user.id, description: "View nested show page")
      redirect_to users_url
    else
      @user = User.find(params[:id])
      render :show
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :taste, :secretsnowman_id, :group)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input
    type='hidden'
    name='authenticity_token'
    value='#{form_authenticity_token}'>".html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecretSnowman</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Amatic+SC' rel='stylesheet' type='text/css'></head>
  <link href='https://fonts.googleapis.com/css?family=Parisienne' rel='stylesheet' type='text/css'>

</head>
<body>
    <div class="banner">
      Secret Snowman
    </div>
    <% if logged_in? %>
      <div class="navbar">
        <nav class="navbar navbar-default">
          <ul class="nav nav-pills">
            <li class="logout"><%= button_to "Log Out", session_url, method: :delete, class: "log-out" %></li>
            <li><a class="<%= params[:action] == "index" && !params[:user_id] ? "active" : "" %>" href="<%= users_url %>">Home</a></li>

            <% if current_user.secretsnowman_id %>
            <%    url = user_secretsnowman_url(current_user[:id], current_user[:secretsnowman_id]) %>
            <% else %>
            <%    url = user_secretsnowman_index_url(current_user[:id]) %>
            <% end %>

            <li><a class="<%= params[:user_id] ? "active" : "" %>" href="<%= url %>">My Secret Snowman</a></li>
            <li><a class="<%= params[:action] == "edit" ? "active" : "" %>"href="<%= edit_user_url(current_user) %>">My Profile</a></li>
          </ul>
        </nav>
      </div>
    <main class="content">
      <p class="current_user">Hi <%= current_user.name %>!</p>
    <% else %>
    <main class="content">
    <% end %>

    <div class="container slider">
      <p class="errors"><%= render "layouts/errors" %></p>
      <%= yield %>
    </div>
  </main>
</body>
</html>

app/views/users/edit.html.erb
<% if current_user == @user %>
  <h2>Update Your Interests</h2>
  <br>
  <p class="interests">Here is where you can express to your fellow
    Secret Snowpeople your gift wishes for this holiday season.
    <br>
    <br>
    Give your secret snowman an idea of what to get you!
  </p>
  <br>
  <form action="<%= user_url(@user) %>" method="post">
    <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
    <input name="_method" type="hidden" value="patch">
      <label class="interests">Material desires:
        <br>
      <textarea name="user[taste]" rows="5" cols="50"
        value="<%= @user.taste %>"><%= @user.taste %></textarea>
      </label>
      <br>
      <input type="submit" value="Update Profile">
  </form>
<% end %>

app/views/users/index.html.erb
<%= auth_token %>
<div class="scroll">
  <img src=<%=asset_path "scroll-design.png"%> alt="" />
</div>
<div class="headline">
  Participants
</div>
<br>
<div class="users">
  <% @users.each do |user| %>
    <%= link_to user.name, user_url(user) %>
  <br>
  <% end %>
</div>
<div class="scroll">
  <img src=<%=asset_path "scroll-design-switched.png"%> alt="" />
</div>

app/views/users/new.html.erb
<div class="jumbotron">
<h1>New Elf</h1>
<br>
<form action="<%= users_url %>" method="post">
  <%= auth_token %>
  <div class="form-group">
    <label for="user_name">Name</label>
    <br>
    <input
      type="text"
      name="user[name]"
      value="<%= @user.name %>"
      id="user_name">
  </div>
  <div class="form-group">
    <label for="user_password">Password</label>
    <br>
    <input type="password" name="user[password]" id="user_password">
  </div>
  <div class="form-group">
    <label for="user_group">Group</label>
    <br>
    <select id="user_group" name="user[group]">
      <option disabled selected value="-- Please Select --">-- Please Select --</option>
      <% User.groups.each do |group| %>
        <option value="<%= group %>"><%= group %></option>
      <% end %>
    </select>
  </div>
  <input type="submit" class="btn btn-success btn-lg" value="Sign Up">
</form>
<br>
<%= link_to "Already have an account?  Log In!", login_url%>
</div>

app/views/users/show.html.erb
<div class="jumbotron">

  <p class="interests">
    <%= @user.name %> wants:
    <br>
    <br>
    <%= @user.taste %>
    <br>
    <% if current_user == @user %>
      <br>
      <%= link_to "Edit", edit_user_url(@user) %>
    <% end %>
  </p>
</div>